### ISSUE TITLE
issue with appveyor

### ISSUE THREAD

**Issue by bcoe** [yargs/set-blocking#9]
@JaKXz I've configured appveyor, it looks like there's a slight issue:

https://ci.appveyor.com/project/bcoe/set-blocking

Should be easier to debug now that appveyor is actually turned on 👍

**Comment by maxrimue** [comment]
@bcoe The issue here is that the AppVeyor requires the configuration to include a `matrix` key when there's multiple Node versions required I think:
```yml
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
```

Running the tests on Windows locally, I've also found they won't pass. This is because the test fixture files call node via a shebang in the heading (`#!/usr/bin/env node`) which doesn't work on Windows as its an entirely different environment, working on a fix for both.
